# Generated by Django 4.1.7 on 2023-02-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordernumber',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordernumber',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderNumber',
        ),
    ]
