# Generated by Django 4.1.7 on 2023-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_images_options_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='uploads/category/'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(upload_to='uploads/Product_Images/'),
        ),
    ]
